#spring:
#  application:
#
#    name: application-service
#
#  mvc:
#    servlet:
#      path: /application-service
#    hiddenmethod:
#      filter:
#        enabled: true
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
cloud:
  aws:
    credentials:
      access-key: AKIAQAVS53U3H4ZOZB6K
      secret-key: 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
      useDefaultAwsCredentialsChain: true
    region:
      static: us-east-1
    bucket:
      name: beaconfire-group-project-bucket
    stack:
      auto: false

application:
  bucket:
    name: beaconfire-group-project-bucket